### ISSUE TITLE
robustImageReading support on podman

### ISSUE THREAD

**Issue by arisjr** [iped-docker/iped#13]
The IPED robustImageReading feature is currently not supported on podman. 

Check if it's possible to correct this problem, found on the unprivileged user feature request (https://github.com/iped-docker/iped/issues/10).

**Comment by arisjr** [comment]
I tested various possibilities of podman security and namespace possible problems with no success.

It was checked with @lfcnassif that there was a conflict of libraries inside IPED lib directory, that, when running the container on podman, an undesired class from one library (spring-jcl-5.3.23.jar) was incorrectly loaded, overwriting the correct class, causing the errors seen at the logs bellow. 

```
[...]
2023-03-06 13:58:51     [INFO]  [engine.datasource.SleuthkitReader]                     Creating database /mnt/setec/TESTE/sleuth.db
2023-03-06 13:58:51     [INFO]  [engine.datasource.SleuthkitReader]                     /mnt/setec/TESTE/sleuth.db database created
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 7: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 7, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-7]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 4: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 4, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-4]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 10: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 10, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-10]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 3: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 3, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-3]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 2: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 2, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-2]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 8: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 8, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-8]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 11: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 11, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-11]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 9: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 9, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-9]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 1: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 1, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-1]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 6: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 6, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-6]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 0: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 0, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-0]
2023-03-06 13:58:51     [INFO]  [engine.sleuthkit.SleuthkitClient]                      Starting SleuthkitServer 5: [java, -cp, /opt/IPED/iped-4.1.0/lib/*:/usr/share/java/sleuthkit-4.12.0.jar, -Xmx128M, iped.engine.sleuthkit.SleuthkitServer, /mnt/setec/TESTE/sleuth.db, 5, /mnt/ipedtmp/iped-temp6016763558996141499/pipe-5]
2023-03-06 13:58:52     [MSG]   [processing.ui.ProgressConsole]                 Inicializando...
2023-03-06 13:58:52     [MSG]   [processing.ui.ProgressConsole]                 Inicializando...
2023-03-06 13:58:52     [INFO]  [engine.sleuthkit.SleuthkitClient$2]                    SleuthkitServer 4: java.lang.NoSuchMethodError: 'void org.apache.commons.logging.LogFactory.setAttribute(java.lang.String, java.lang.Object)'
2023-03-06 13:58:52     [INFO]  [engine.sleuthkit.SleuthkitClient$2]                    SleuthkitServer 4: at iped.engine.config.Configuration.configureLogger(Configuration.java:86)
        at iped.engine.config.Configuration.getConfiguration(Configuration.java:101)
        at iped.engine.config.Configuration.loadConfigurables(Configuration.java:166)
        at iped.engine.config.Configuration.loadConfigurables(Configuration.java:143)
        at iped.engine.sleuthkit.SleuthkitServer.main(SleuthkitServer.java:71)
java.lang.Exception: Error starting SleuthkitServer 4
        at iped.engine.sleuthkit.SleuthkitClient.start(SleuthkitClient.java:219)
        at iped.engine.sleuthkit.SleuthkitClient.<init>(SleuthkitClient.java:166)
        at iped.engine.sleuthkit.SleuthkitClient$1.run(SleuthkitClient.java:141)
[...]
```

This error is known to other projects (https://github.com/spring-projects/spring-framework/issues/20611).

**The library spring-jcl-5.3.23.jar was removed from IPED lib directory in the container and this action permitted IPED to process successfully the test evidence without errors.**

Waiting for @lfcnassif to validate the lib deletion.

**Comment by lfcnassif** [comment]
I have to ask on Tika project first to be sure it is safe to be deleted, since that library was brought by Tika. Surprisingly it conflicts with another library used by Tika, so it looks like the bug was caused by a Tika bug...

**Comment by lfcnassif** [comment]
Waiting Tika feedback: https://github.com/sepinf-inc/IPED/issues/1572#issuecomment-1457360982

**Comment by lfcnassif** [comment]
No feedback from them, but I did some tests and they passed. https://github.com/sepinf-inc/IPED/issues/1572 was closed removing spring-jcl and commons-logging. Thanks @arisjr for providing detailed logging messages.

**Comment by arisjr** [comment]
Thanks again, @lfcnassif, to help us to solve the problem.

For now, while there's no update release from IPED, I will manually remove those two libraries on the container build.

**Comment by lfcnassif** [comment]
Tika's project leader answered commons-logging usage is outdated, possibly someone forgot to remove it.

**Comment by lfcnassif** [comment]
A safer comment from the one responsible for Tika logging refactoring years ago:
https://issues.apache.org/jira/browse/TIKA-2245?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17698065#comment-17698065

**Comment by arisjr** [comment]
I did some tests and the @lfcnassif proposed correction is working fine. 

@mobab-th, (https://github.com/iped-docker/iped/issues/10 creator) you don't need to disable robustImageReading on podman no more.

Closing this issue.
